version: '2'

services:
        app:
            build: .
            working_dir: /app
            command: sh -c "python manage.py collectstatic --noinput &&
                                python manage.py migrate &&
                                daphne -b 0.0.0.0 -p 80 site_config.asgi:application"
            volumes:
                - ./data/:/app/data
                - ./config/:/app/config
                - /etc/localtime:/etc/localtime:ro
            ports:
                - "80:80"
