# Generated by Django 2.1.5 on 2023-01-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stop_reasons', '0002_auto_20221018_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60)),
                ('hexcolor', models.CharField(default='#ff0000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='reason',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stop_reasons.Category'),
        ),
    ]
