# Generated by Django 3.2.16 on 2023-08-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop_reasons', '0004_machine_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
