{
 "title": "Machine Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "machine",
    "query": "from(bucket: \"stoppage_monitoring\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n  |> keep(columns: [\"machine_name\"])\n  |> distinct(column: \"machine_name\")\n  |> filter(fn: (r) => r[\"machine_name\"] != \"null\")\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n |> sort(columns: [\"_time\"])\n |> last(column: \"_time\")\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n//  |> filter(fn: (r) => r[\"_field\"] == \"running\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => not exists r[\"status\"] or r[\"status\"] != \"Shift End\")\n  |> group(columns: [\"running\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"running\"], valueColumn: \"duration\")\n  |> keep(columns: [\"true\",\"false\"])\n  |> map(fn: (r) => ({r with utilisation: if exists r.false and r.false!=0 then (if exists r.true then float(v:r.true) / float(v:r.true+r.false) *100.0 else 0.0) else 100.0}))\n  |> keep(columns: [\"utilisation\"])"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n//  |> filter(fn: (r) => r[\"_field\"] == \"running\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n |> last(column: \"_time\")\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n//  |> filter(fn: (r) => r[\"_field\"] == \"running\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => not exists r[\"status\"] or r[\"status\"] != \"Shift End\")\n  |> group(columns: [\"running\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"running\"], valueColumn: \"duration\")\n  |> keep(columns: [\"true\",\"false\"])\n  |> map(\n    fn: (r) => ({r with false: if exists r.false then r.false else 0, true: if exists r.true then r.true else 0}),\n  )"
    }
   ]
  },
  {
   "title": "Number of Stops",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> duplicate(column: \"_value\", as: \"buckets\")\n  |> group(columns: [\"buckets\"], mode: \"by\")\n  |> filter(fn: (r) => r[\"buckets\"] != \"Running\" and r[\"buckets\"] != \"Shift End\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Time spent stopped",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> drop(columns: [\"_start\",\"_stop\",\"status\"])\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> duplicate(column: \"_value\",as: \"bucket\")\n  |> group(columns: [\"bucket\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"bucket\"], valueColumn: \"duration\")\n  |> drop(columns: [\"Running\", \"Shift End\"])\n  "
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"date\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> filter(fn: (r) => r[\"machine_name\"] == \"${machine}\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\ndataset\n |> keep(columns: [\"_value\",\"_time\"])"
    }
   ]
  }
 ]
}