{
 "title": "Overview Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Utilisation",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n |> sort(columns: [\"_time\"])\n |> last(column: \"_time\")\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => not exists r[\"status\"] or r[\"status\"] != \"Shift End\")\n  |> group(columns: [\"running\",\"machine_name\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"running\"], valueColumn: \"duration\")\n  |> map(fn: (r) => ({r with utilisation: if exists r.false and r.false!=0 then (if exists r.true then float(v:r.true) / float(v:r.true+r.false) *100.0 else 0.0) else 100.0}))\n  |> keep(columns: [\"utilisation\",\"machine_name\"])"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n//  |> filter(fn: (r) => r[\"_field\"] == \"running\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n |> last(column: \"_time\")\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n//  |> filter(fn: (r) => r[\"_field\"] == \"running\")\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n |> keep(columns: [\"_time\",\"running\",\"status\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => not exists r[\"status\"] or r[\"status\"] != \"Shift End\")\n  |> group(columns: [\"running\",\"machine_name\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"running\"], valueColumn: \"duration\")\n  |> group()\n  |> map(\n    fn: (r) => ({r with false: if exists r.false then r.false else 0, true: if exists r.true then r.true else 0}),\n  )"
    }
   ]
  },
  {
   "title": "Machine States",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 0 },
   "targets": [
    {
     "query": "import \"date\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\ndataset\n  |> keep(columns: [\"_time\",\"_value\",\"machine_name\"])"
    }
   ]
  },
  {
   "title": "Total Number of Stops",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_id\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_id\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> duplicate(column: \"_value\", as: \"buckets\")\n  |> group(columns: [\"buckets\"], mode: \"by\")\n  |> filter(fn: (r) => r[\"buckets\"] != \"Running\" and r[\"buckets\"] != \"Shift End\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Total Time Stopped",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_id\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_id\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> drop(columns: [\"_start\",\"_stop\",\"status\"])\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> duplicate(column: \"_value\",as: \"bucket\")\n  |> group(columns: [\"bucket\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"bucket\"], valueColumn: \"duration\")\n  |> drop(columns: [\"Running\"])\n  |> drop(columns: [\"Shift End\"])\n  "
    }
   ]
  },
  {
   "title": "Fault Times",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\nimport \"contrib/tomhollingworth/events\"\n\nstart = from(bucket: \"stoppage_monitoring\")\n |> range(start: date.sub(d:1d,from:v.timeRangeStart), stop: v.timeRangeStart)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n |> last()\n |> map(fn: (r) => ({r with _time: v.timeRangeStart}))\n\nbody = from(bucket: \"stoppage_monitoring\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"fault_tracking\")\n |> filter(fn: (r) => r[\"_field\"] == \"status\")\n |> keep(columns: [\"_time\",\"_value\",\"_field\",\"machine_name\"])\n\ndataset = union(tables: [start,body])\n\n\ndataset\n  |> drop(columns: [\"_start\",\"_stop\",\"status\"])\n  |> sort(columns: [\"_time\"])\n  |> events.duration(unit: 1s, stop: v.timeRangeStop)\n  |> duplicate(column: \"_value\",as: \"bucket\")\n  |> group(columns: [\"bucket\",\"machine_name\"])\n  |> sum(column: \"duration\")\n  |> pivot(rowKey: [], columnKey: [\"bucket\"], valueColumn: \"duration\")\n  |> drop(columns: [\"Running\",\"Shift End\"])\n  |> group()\n  |> map(fn: (r) => ({r with _time: v.timeRangeStart, machine_name: string(v:r.machine_name)+\":\"}))"
    }
   ]
  }
 ]
}